Check files empty

diff --git a/.github/workflows/01-setup.yaml b/.github/workflows/01-setup.yaml
--- a/.github/workflows/01-setup.yaml
+++ b/.github/workflows/01-setup.yaml
@@ -46,7 +46,20 @@ jobs:
         # Needed by the "flutterfire bundle-service-file" build phase in Xcode
         dart pub global activate flutterfire_cli 1.0.1 --overwrite
 
-        cat lib/firebase_options_${{ env.DEPLOY_ENV }}.dart
+        # Check if files are empty
+        for file in \
+          "lib/firebase_options_${{ env.DEPLOY_ENV }}.dart" \
+          "android/app/src/${{ env.DEPLOY_ENV }}/google-services.json" \
+          "ios/flavors/${{ env.DEPLOY_ENV }}/GoogleService-Info.plist" \
+          "firebase.json"
+        do
+          if [ ! -s "$file" ]; then
+            echo "ERROR: $file is empty!"
+            exit 1
+          else
+            echo "$file exists and is not empty ($(wc -c < "$file") bytes)"
+          fi
+        done
 
     - name: Upload build files
       uses: actions/upload-artifact@v4
